title: learning to code with edabits
theme: minima
author: sweetwinterscenery
email: plilwowz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  learnin how to code

# social links
twitter_username: plilwowz # DO NOT include the @ character, or else the build will fail!
github_username:  sweetwinterscenery # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
